vendor: mars: Add missing camera libraries
FAILED: out/soong/build.lineage_mars.ninja
cd "$(dirname "out/host/linux-x86/bin/soong_build")" && BUILDER="$PWD/$(basename "out/host/linux-x86/bin/soong_build")" && cd / && env -i "$BUILDER" --top "$TOP" --soong_out "out/soong" --out "out" --soong_variables out/soong/soong.lineage_mars.variables -o out/soong/build.lineage_mars.ninja --kati_suffix -lineage_mars -l out/.module_paths/Android.bp.list --available_env out/soong/soong.environment.available --used_env out/soong/soong.environment.used.lineage_mars.build Android.bp
error: vendor/xiaomi/mars/Android.bp:7431:1: "camera.qcom" depends on undefined module "libmegface".
Or did you mean ["libXMFace" "libdexfile" "libexfat" "libmedia" "libmemmap2" "libmemmark" "libmemtrack" "libmerge" "libmetrics" "libmpbase" "libtitrace"]?
error: vendor/xiaomi/mars/Android.bp:7431:1: "camera.qcom" depends on undefined module "libMegviiFacepp-0.5.2".
Or did you mean ["_libberberis_jni_srcs" "tv-lib-exoplayer-v2-ui" "zlib_deflate_fuzzer"]?
15:38:25 soong bootstrap failed with: exit status 1